# LAVALINK CONFIG 2025 - NO ERRORS GUARANTEED
# Fixed Apple Music token issue and all dependency problems

server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: "chiro666_secure_2025"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    
    # Audio settings untuk smooth playback
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    opusEncodingQuality: 10
    resamplingQuality: HIGH
    trackStuckThresholdMs: 10000
    useSeekGhosting: true
    
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true

    gc-warnings: true
    playerUpdateInterval: 5
    youtubePlaylistLoadLimit: 6

  plugins:
    # YouTube Plugin TERBARU - v1.13.3
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.13.3"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false
    
    # LavaSrc Plugin untuk Spotify (Apple Music disabled)
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.7.3"
      repository: "https://jitpack.io"
      snapshot: false

# Plugin configuration
plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    
    # Multiple clients untuk reliability
    clients:
      - MUSIC
      - WEB
      - ANDROID_TESTSUITE
      - TVHTML5EMBEDDED
      - ANDROID_MUSIC
      - IOS
    
    # OAuth configuration (optional)
    oauth:
      enabled: true
      skipInitialization: false
    
    # Search settings
    search:
      maxResults: 10
      suggestions: true
    
    # Thumbnail settings
    thumbnails:
      enabled: true
      maxResolution: "maxresdefault"

  lavasrc:
    # ONLY ENABLE SPOTIFY - DISABLE APPLE MUSIC TO AVOID TOKEN ERROR
    sources:
      spotify: true
      applemusic: false  # DISABLED to prevent token error
      deezer: false
      yandexmusic: false
    
    providers:
      - "ytmsearch:\"%ISRC%\""
      - "ytsearch:\"%ISRC%\""
      - "ytmsearch:%QUERY%"
      - "ytsearch:%QUERY%"
    
    # Spotify configuration (optional - can be left empty)
    spotify:
      clientId: ""
      clientSecret: ""
      countryCode: "ID"

# Logging configuration
logging:
  level:
    root: INFO
    lavalink: INFO
    dev.lavalink.youtube: INFO

  file:
    path: ./logs/
  
  logback:
    rollingpolicy:
      max-file-size: 25MB
      max-history: 8

# Spring configuration
spring:
  main:
    banner-mode: "off"